### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by ArcAIN6** [xpix/XLCD#2]
Since i don't have an XStepper, is there a way to use this using an arduino Uno with GRBL on it, and an Arduino Mega? 

I.e. PC <=> Mega[LCD, Keypad, menu system etc] <=> Uno[GRBL]

**Comment by xpix** [comment]
Sure, xlcd are only a proxy between PC and GRBL. XLCD get data from PC and send this 1:1 to GRBL.

**Comment by ArcAIN6** [comment]
So i can just load this onto the mega? Or do i need to build the LCD module shown on the front page, and load XLCD onto that?

The only reason i ask, is i live in the middle of nowhere, and ordering parts means waiting a minimum of 25 days before they arrive. So if i can get away with just using the mega+uno, that would be great.

**Comment by xpix** [comment]
Try an UNO or other Arduino first and please use version 0.3 https://github.com/xpix/XLCD/tree/xlcd-0.3. For an mega you have change the pins for serial ports.

**Comment by ArcAIN6** [comment]
will give it a shot now :) So happy this exists.

**Comment by ArcAIN6** [comment]
hrm. I seem to have run into an error on verifying. Getting error on line 14 of lcd_screens.

Is there an error with the actual code, or am i using outdated libraries (Using the libraries supplied  by the wiki.)

lcd_screens:14: error: #elif with no expression
commands.ino: In function 'void learn_button()':
commands:46: error: 'BUTTONS_A_ADC_PIN' was not declared in this scope
commands:48: error: 'BUTTONS_B_ADC_PIN' was not declared in this scope
commands.ino: In function 'void press_button(String)':
commands:61: error: 'getValue' was not declared in this scope
commands.ino: In function 'void setinterval(String)':
commands:75: error: 'getValue' was not declared in this scope
commands.ino: In function 'void memoryfree()':
commands:94: error: 'freeMemory' was not declared in this scope
console.ino: In function 'void resetDevice(int)':
console:146: error: redefinition of 'void resetDevice(int)'
commands:86: error: 'void resetDevice(int)' previously defined here
#elif with no expression

**Comment by xpix** [comment]
I have no idea :) i realize this 2 years ago! 
But maybe i can send you an Arduino IDE that works with it. Please check also the forum in shapeoko, some peoples try to make it better http://www.shapeoko.com/forum/viewtopic.php?f=11&t=1904&p=50530&hilit=XLCD#p50530

My Advice, remove all button and unused functions and try to make it only with LCD and Serial sniffing :)

**Comment by xpix** [comment]
Please try to compile this fork:

https://github.com/soundstorm/XLCD

**Comment by ArcAIN6** [comment]
wierd... it seems to verify with arduino IDE 1.5.4, but not the latest.. 

however, i think there's going to be a lot of tinkering on my end, as the LCD i have is an LCD keypad shield with 5 buttons + reset, and there is no RW pin. 
I'll see if i can figure out a workaround.. 

```
Pin 4 (DB4)
Pin 5 (DB5)
Pin 6 (DB6)
Pin 7 (DB7)
Pin 8 (RS)
Pin 9 (Enable)
Pin 10 (Backlight)
Analog 0 - Push button switches
```

**Comment by ArcAIN6** [comment]
well.. i couldn't really figure out how to get it to work. So i started all over and have been writing something based upon my own hardware.. It is way less complex than yours of coarse, and there aren't a lot of features. But if you are interested, i have uploaded it to one of my domains, and maybe you can take a look at it, give some advice or pointers where i can easily add features, or simplify things. 

http://www.thegamerzhost.com/LCDKeypadMenuTemplate2.rar
